import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        {/* <div className="layout-shell min-h-full"> */}
        {/* <div className="layout-grid min-h-full"> */}
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
        {/* </div> */}
        {/* </div> */}
      </body>
    </html>
  );
}
